name: CI

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
          cache: true

      - name: Build (sanity)
        run: go build ./...

      - name: Test
        run: go test ./...

  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os:   [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]

    env:
      CGO_ENABLED: 0

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
          cache: true

      - name: Compute VERSION
        id: ver
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            V="${GITHUB_REF_NAME#v}"
          else
            V="$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$V" >> "$GITHUB_ENV"
          echo "version=$V" >> "$GITHUB_OUTPUT"

      - name: Build binary
        shell: bash
        run: |
          mkdir -p dist
          EXT=""
          [[ "${{ matrix.os }}" == "windows" ]] && EXT=".exe"
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -trimpath \
            -ldflags="-s -w -X main.version=${VERSION}" \
            -o "dist/gommit${EXT}" ./cmd/gommit

      - name: Package
        id: pkg
        shell: bash
        run: |
          cd dist
          NAME="gommit_${{ steps.ver.outputs.version }}_${{ matrix.os }}_${{ matrix.arch }}"
          EXT=""
          [[ "${{ matrix.os }}" == "windows" ]] && EXT=".exe"
          BIN="gommit${EXT}"

          # Verificar se o binário foi criado
          if [[ ! -f "$BIN" ]]; then
            echo "❌ Binary not found: $BIN"
            ls -la
            exit 1
          fi

          mkdir "$NAME"
          cp "$BIN" "$NAME/"
          
          # Incluir docs (se existirem no repo)
          for f in ../README.md ../LICENSE ../CONTRIBUTING.md; do
            [[ -f "$f" ]] && cp "$f" "$NAME/" || true
          done

          # Criar pacote
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            zip -r "${NAME}.zip" "$NAME"
            ASSET_PATH="${NAME}.zip"
            echo "✅ Created Windows package: $ASSET_PATH"
          else
            tar -czf "${NAME}.tar.gz" "$NAME"
            ASSET_PATH="${NAME}.tar.gz"
            echo "✅ Created Unix package: $ASSET_PATH"
          fi
          
          # Verificar se o pacote foi criado
          if [[ ! -f "$ASSET_PATH" ]]; then
            echo "❌ Package creation failed: $ASSET_PATH"
            exit 1
          fi
          
          echo "asset=$ASSET_PATH" >> "$GITHUB_OUTPUT"
          echo "package_name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pkg.outputs.package_name }}
          path: dist/${{ steps.pkg.outputs.asset }}
          if-no-files-found: error
          compression-level: 0

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List downloaded files
        shell: bash
        run: |
          echo "📦 Downloaded artifacts:"
          find dist -type f -name "*.tar.gz" -o -name "*.zip" | sort
          
      - name: Generate checksums
        shell: bash
        run: |
          cd dist
          shopt -s nullglob
          rm -f SHA256SUMS.txt
          
          echo "🔐 Generating checksums..."
          for f in *.tar.gz *.zip; do
            if [[ -f "$f" ]]; then
              sha256sum "$f" >> SHA256SUMS.txt
              echo "✅ $f"
            fi
          done
          
          if [[ -f SHA256SUMS.txt ]]; then
            echo ""
            echo "📋 SHA256 checksums:"
            cat SHA256SUMS.txt
          else
            echo "❌ No files found for checksum generation"
            exit 1
          fi

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}